monotonic impl: Fix panic due to timer rollover
After the timer value rolls over the newer more recent value will be
negative. Calculating the duration_since with an older still positive
Instant results in a panic due to subtracting with overflow:

panicked at 'attempt to subtract with overflow', src/monotonic_stm32l0.rs:149:20